export const fetchUrl =
  "https://raw.githubusercontent.com/pvpoke/pvpoke/master/src/data/rankings/gobattleleague/overall/rankings-1500.json";

export const sets = [
  [
    // Past sets
    ["Marowak (Alolan)", "Tropius", "Vigoroth"],
    ["Altaria"],
    ["Altaria", "Stunfisk", "Abomasnow"],
    ["Altaria", "Swampert (Shadow)", "Serperior"],
    ["Azumarill", "Abomasnow", "Medicham"],
    ["Azumarill", "Mandibuzz", "Galvantula"],
    ["Beedrill", "Sableye"],
    ["Clefable", "Azumarill", "Altaria"],
    ["Cofagrigus", "Azumarill", "Bastiodon"],
    ["Cofagrigus", "Vigoroth", "Mandibuzz"],
    ["Deoxys (Defense)", "Victreebel (Shadow)", "Ninetales (Alolan)"],
    ["Deoxys (Defense)", "Azumarill", "Sableye"],
    ["Dewgong", "Azumarill", "Marowak (Alolan)"],
    ["Diggersby", "Vigoroth", "Stunfisk (Galarian)"],
    ["Drifblim", "Obstagoon", "Azumarill"],
    ["Empoleon", "Shiftry"],
    ["Stunfisk (Galarian)", "Azumarill", "Marowak (Alolan)"],
    ["Stunfisk (Galarian)", "Sirfetch'd", "Galvantula"],
    ["Stunfisk (Galarian)", "Galvantula", "Politoed"],
    ["Stunfisk (Galarian)", "Jellicent", "Umbreon"],
    ["Stunfisk (Galarian)", "Venusaur", "Medicham"],
    ["Galvantula", "Azumarill"],
    ["Galvantula", "Azumarill", "Marowak (Alolan)"],
    ["Galvantula", "Azumarill", "Stunfisk"],
    ["Hypno", "Machamp (Shadow)", "Azumarill"],
    ["Mandibuzz", "Stunfisk (Galarian)", "Cresselia"],
    ["Medicham", "Jellicent", "Bastiodon"],
    ["Medicham", "Swampert", "Bastiodon"],
    ["Medicham", "Ninetales (Alolan)", "Cofagrigus"],
    ["Medicham", "Muk", "Skarmory"],
    ["Medicham", "Zapdos (Shadow)", "Victreebel (Shadow)"],
    ["Medicham", "Zapdos (Shadow)", "Wigglytuff"],
    ["Registeel", "Azumarill", "Tropius"],
    ["Sableye", "Scrafty", "Azumarill"],
    ["Serperior", "Jellicent", "Bastiodon"],
    ["Shiftry", "Azumarill", "Marowak (Alolan)"],
    ["Shiftry", "Talonflame", "Azumarill"],
    ["Skarmory", "Azumarill", "Swampert"],
    ["Skarmory", "Obstagoon", "Whiscash"],
    ["Stunfisk (Galarian)", "Machamp (Shadow)", "Abomasnow"],
    ["Stunfisk (Galarian)", "Ferrothorn", "Obstagoon"],
    ["Swampert", "Skarmory", "Froslass"],
    ["Swampert", "Registeel", "Talonflame"],
    ["Swampert", "Azumarill", "Wigglytuff"],
    ["Talonflame", "Nidoqueen (Shadow)", "Bastiodon"],
    ["Talonflame", "Jellicent", "Scrafty"],
    ["Togekiss", "Lapras", "Vigoroth"],
    ["Toxicroak", "Umbreon", "Ninetales (Alolan)"],
    ["Umbreon", "Swampert", "Azumarill"],
    ["Umbreon", "Tropius", "Azumarill"],
    ["Umbreon", "Scrafty", "Nidoqueen"],
    ["Venusaur", "Azumarill", "Stunfisk (Galarian)"],
    ["Venusaur", "Azumarill", "Umbreon"],
    ["Venusaur", "Sableye", "Umbreon"],
    ["Vigoroth", "Azumarill", "Nidoqueen (Shadow)"],
    ["Whiscash", "Azumarill", "Chansey"],
    ["Whiscash", "Skarmory", "Medicham"],
  ],
];

export default sets.flatMap((team) => team);
